// randrunner.js

var runner_list = [
    "Amoeba UK",
    "Exari onU",
    "wer ster",
    "shiru 666",
    "Kukk er",
    "Siz zle",
    "poke guy",
    "Gunner maniac",
    "Swift alu",
    "sco agogo",
    "Mach Wing",
    "Kid Rocker96",
    "Driek iann",
    "edda ket",
    "Wh0mis DS",
    "Casual pokePlayer",
    "Ender born",
    "JP Xinnam",
    "kur ddt",
    "SL weed",
    "Van dio",
    "3rd Jester",
    "slayer lol",
    "5upa mayne",
    "abys mal",
    "Ana nan",
    "cater knees",
    "thewaffle man",
    "wave warrior",
    "dec sy",
    "Extra Tricky",
    "Dabom stew",
    "Keiz aron",
    "gif vex",
    "entr pntr",
    "string flow",
    "New Amber",
    "G Sharkf",
    "Is rar",
    "Jord an97",
    "lucky typhlosion",
    "Mad diicT",
    "Ranger Squid",
    "Sparkle Lanturn",
    "_ PoY",
    "wink market",
    "Æ tienne",
    "thunder _147_",
    "Ti Kevin83",
    "randall eatscheese",
    "ringo 777",
    "mindof damon",
    "que laagging",
    "Vin cento",
    "Sin star",
    "Affected Ashes",
    "Pulse Effects",
    "Juanly ways",
    "Retro tato",
    "line washere",
    "Head bob",
    "Corvi mae",
    "Thomas PatrickWX",
    "Bungied 2TheTree",
    "Garfield TheLightning",
    "head strong",
    "San Jan",
    "Ti ppi",
    "Et chy",
    "fran chewbacca",
    "knox conary",
    "JT MagicMan",
    "Sheltie sci",
    "iron dre_",
    "cooltrainer michael",
    "tru ely",
    "pickle plop",
    "Q palz",
    "zen aga",
    "luck less",
    "LoveSick Hero",
    "bang Yongguk",
    "AnaI Pikachu",
    "Primal Pizza",
    "hwang bro",
    "Yuji ito",
    "Der Teppich",
    "em ray",
    "SquareRoot ofSheep",
    "stoc chi",
    "Teh HammerShow",
    "GoodAt BeingSimple",
    "Econ Sean",
    "I_only_say VoHiYo",
    "Legend Eater",
    "callum bal",
    "Alan Schweitzer",
    "Fract NL",
    "Ocean Bagel",
    "doctor sprinkles",
    "Main 97",
    "themath genius",
    "ryzi ken",
    "Rau flegon",
    "min now",
    "Chub Fish",
    "Boun xii",
    "Ruben tus",
    "Saiyan Cinq",
    "The KRAM",
    "Buster Poke",
    "Money HypeMike",
    "hal qery",
    "The4th GenGamer",
    "Ekman Larsson",
    "ito taka",
    "Oh Snap",
    "ker bis54",
    "jy ash4",
    "aka saka",
    "Ed HeadSR",
    "puny uta",
    "Tucker LeRat",
    "Gimmy Thomas",
    "nerdy nerd32",
    "Kjoe ran",
    "yourfriend Andy",
    "Nix 644",
    "Shen anagans",
    "AB Twisty",
    "TTS 4Life",
    "Al w0",
    "keeping iticy"
  ];

// Function called when the "!randrunner" command is issued
function randrunnerCommand(target, username, client) {
    const firstName = getRandomNamePart(runner_list, 0); // Get random first name part
    const lastName = getRandomNamePart(runner_list, 1); // Get random last name part
  
    const combinedName = `${firstName}${lastName}`;
    client.say(target, `@${username} Your random runner name is: ${combinedName}`);
  }
  
  // Helper function to get a random name part from the list
  function getRandomNamePart(nameList, partIndex) {
    const filteredList = nameList.map((name) => name.split(' ')[partIndex]);
    const randomIndex = Math.floor(Math.random() * filteredList.length);
    return filteredList[randomIndex];
  }
  
  module.exports = {
    randrunnerCommand,
  };