// hangmanBot.js

const HangmanGame = require('./hangmanGame');

const { sanitizeInput } = require('../handlers/sanitizer');
const { Random } = require('random-js');

const hangmanChannels = {};
const hangmanCooldowns = {}; // Store cooldown timestamps for !hangman command

function startHangman(target, client) {
  if (hangmanChannels[target]?.cooldown) {
    return;
  }

  const runners = [
    "AmoebaUK",
    "ExarionU",
    "werster",
    "Shiru666",
    "Kukker",
    "sizzleskeleton",
    "pokeguy",
    "Gunnermaniac",
    "Swiftalu",
    "scoagogo",
    "MachWing",
    "driekiann",
    "eddaket",
    "Wh0misDS",
    "CasualPokePlayer",
    "Enderborn",
    "JPXinnam",
    "kurddt",
    "SLweed",
    "Vandio",
    "3rdJester",
    "SlayerLoL99",
    "5upamayne",
    "crafted",
    "Ananan",
    "caterknees",
    "thewaffleman",
    "WaveWarrior",
    "decsy",
    "ExtraTricky",
    "Dabomstew",
    "Keizaron",
    "gifvex",
    "entrpntr",
    "stringflow",
    "NewAmber",
    "GShark54",
    "israrcool22",
    "Jordan97",
    "luckytyphlosion",
    "MaddiicT",
    "RangerSquid",
    "Sparkle",
    "PoY",
    "winkmarket",
    "AEtienne",
    "thunder147",
    "TiKevin83",
    "randalleatscheese",
    "ringo777",
    "mindofdamon",
    "Quelaagging",
    "Vincento",
    "Sinstar",
    "AffectedAshes",
    "PulseEffects",
    "Juanlyways",
    "Retrotato",
    "linewashere",
    "Headbob",
    "Corvimae",
    "ThomasPatrickWX",
    "Bungied2thetree",
    "GarfieldTheLightning",
    "headstrong1290",
    "Sanjan",
    "Tippi",
    "Etchy",
    "franchewbacca",
    "knoxconary",
    "JTMagicman",
    "SheltieSci",
    "Irondre",
    "cooltrainermichael",
    "truely",
    "PicklePlop",
    "Qpalz98",
    "Araya",
    "Luckless",
    "LoveSickHero",
    "BangYongGuk97",
    "Analpikachu",
    "primalpizza",
    "hwangbro",
    "Yujito",
    "DerTeppich",
    "emray",
    "squaresr",
    "stocchi",
    "TehHammerShow",
    "GoodAtBeingSimple",
    "EconSean",
    "IonlysayVoHiYo",
    "LegendEater",
    "callumbal",
    "AlanSchweitzer",
    "FractNL",
    "OceanBagel",
    "Crrool",
    "Main97",
    "themathgenius",
    "ryziken",
    "zekeke",
    "minnow",
    "TheLimeFilms",
    "Bounxii",
    "Rubentus",
    "SaiyanCinq",
    "TheKRAM",
    "Busterpoke",
    "MoneyHypeMike",
    "halqery",
    "The4thGenGamer",
    "EkmanLarsson",
    "itotaka1031",
    "OhSnap",
    "kerbis54",
    "jyash4",
    "zypotic",
    "EdHeadSR",
    "punyuta",
    "TuckerLeRat",
    "Gimmy",
    "nerdynerd32",
    "Kjoeran",
    "chippytoothy",
    "Nix644",
    "Shenanagans",
    "ABTwisty",
    "TTS4Life",
    "Alw0",
    "keepingiticy",
    "BluMagma",
    "epicdudeguy",
    "Kyutora",
    "billbonzai",
    "Galino",
    "Paraz10",
    "uwsellan",
    "Sylwer328",
    "Matt59620",
    "Slywoo",
    "Cayoche",
    "Wharax",
    "splendidz",
    "Yaksooo",
    "wartab",
    "tahis9",
    "Hypnoshark",
    "Prabxz",
    "Dakuuu",
    "Jielefe",
    "FlameSR",
    "MystS4",
    "Plotwyx",
    "bahamut3359",
    "HE4TR4N",
    "BeberVorpal",
    "LucasPGLP",
    "Vadnika",
    "Cerpin",
    "prieR57",
    "Noylls",
    "joylin728",
    "Aspect",
    "Grogir"
  ];

  const items = [
    "Ability Capsule",
    "Ability Patch",
    "Ability Shield",
    "Ability Urge",
    "Abomasite",
    "Absolite",
    "Absorb Bulb",
    "Adamant Crystal",
    "Adamant Mint",
    "Adamant Orb",
    "Adrenaline Orb",
    "Aerodactylite",
    "Aggronite",
    "Aguav Berry",
    "Air Balloon",
    "Alakazite",
    "Aloraichium Z",
    "Altarianite",
    "Ampharosite",
    "Amulet Coin",
    "Antidote",
    "Apicot Berry",
    "Apricorn",
    "Armor Fossil",
    "Armorite Ore",
    "Aspear Berry",
    "Assault Vest",
    "Audinite",
    "Auspicious Armor",
    "Aux Evasion",
    "Aux Guard",
    "Aux Power",
    "Aux Powerguard",
    "Awakening",
    "Babiri Berry",
    "Ball of Mud",
    "Balm Mushroom",
    "Banettite",
    "Beach Glass",
    "Beast Ball",
    "Beedrillite",
    "Belue Berry",
    "Berry Juice",
    "Berry Sweet",
    "Bicycle",
    "Big Malasada",
    "Big Mushroom",
    "Big Nugget",
    "Big Pearl",
    "Big Root",
    "Binding Band",
    "Bitter Herba Mystica",
    "Black Apricorn",
    "Black Augurite",
    "Black Belt",
    "Black Flute",
    "Black Glasses",
    "Black Sludge",
    "Black Tumblestone",
    "Blank Plate",
    "Blastoisinite",
    "Blazikenite",
    "Blue Apricorn",
    "Blue Flute",
    "Blue Scarf",
    "Blue Shard",
    "Bluk Berry",
    "Blunder Policy",
    "Bold Mint",
    "Booster Energy",
    "Bottle Cap",
    "Brave Mint",
    "Bright Powder",
    "Bug Gem",
    "Bug Memory",
    "Bug Tera Shard",
    "Buginium Z",
    "Burn Drive",
    "Burn Heal",
    "Calcium",
    "Calm Mint",
    "Cameruptite",
    "Carbos",
    "Careful Mint",
    "Casteliacone",
    "Cell Battery",
    "Chalky Stone",
    "Charcoal",
    "Charizardite X",
    "Charizardite Y",
    "Charti Berry",
    "Cheri Berry",
    "Cherish Ball",
    "Chesto Berry",
    "Chilan Berry",
    "Chill Drive",
    "Chipped Pot",
    "Choice Band",
    "Choice Scarf",
    "Choice Specs",
    "Chople Berry",
    "Claw Fossil",
    "Cleanse Tag",
    "Clear Amulet",
    "Clever Feather",
    "Clever Mochi",
    "Clover Sweet",
    "Coba Berry",
    "Colbur Berry",
    "Comet Shard",
    "Cornn Berry",
    "Courage Candy",
    "Courage Candy L",
    "Courage Candy XL",
    "Cover Fossil",
    "Covert Cloak",
    "Cracked Pot",
    "Custap Berry",
    "Damp Rock",
    "Dark Gem",
    "Dark Memory",
    "Dark Tera Shard",
    "Darkinium Z",
    "Dawn Stone",
    "Decidium Z",
    "Deep Sea Scale",
    "Deep Sea Tooth",
    "Destiny Knot",
    "Diancite",
    "Dire Hit",
    "Direshroom",
    "Discount Coupon",
    "Discovery Slate",
    "Distortion Slate",
    "Dive Ball",
    "DNA Splicers",
    "Dome Fossil",
    "Douse Drive",
    "Draco Plate",
    "Dragon Fang",
    "Dragon Gem",
    "Dragon Memory",
    "Dragon Scale",
    "Dragon Tera Shard",
    "Dragonium Z",
    "Dread Plate",
    "Dream Ball",
    "Dubious Disc",
    "Durin Berry",
    "Dusk Ball",
    "Dusk Stone",
    "Dynamax Candy",
    "Dynite Ore",
    "Earth Plate",
    "Eevium Z",
    "Eject Button",
    "Eject Pack",
    "Electirizer",
    "Electric Gem",
    "Electric Memory",
    "Electric Seed",
    "Electric Tera Shard",
    "Electrium Z",
    "Elixir",
    "Energy Powder",
    "Energy Root",
    "Enigma Berry",
    "Escape Rope",
    "Ether",
    "Everstone",
    "Eviolite",
    "Exp Candy L",
    "Exp Candy M",
    "Exp Candy S",
    "Exp Candy XL",
    "Exp Candy XS",
    "Exp Share",
    "Expert Belt",
    "Fairium Z",
    "Fairy Gem",
    "Fairy Memory",
    "Fairy Tera Shard",
    "Fast Ball",
    "Feather Ball",
    "Fighting Gem",
    "Fighting Memory",
    "Fighting Tera Shard",
    "Fightinium Z",
    "Figy Berry",
    "Fire Gem",
    "Fire Memory",
    "Fire Stone",
    "Fire Tera Shard",
    "Firium Z",
    "Fist Plate",
    "Flame Orb",
    "Flame Plate",
    "Float Stone",
    "Flower Sweet",
    "Fluffy Tail",
    "Flying Gem",
    "Flying Memory",
    "Flying Tera Shard",
    "Flyinium Z",
    "Focus Band",
    "Focus Sash",
    "Fossilized Bird",
    "Fossilized Dino",
    "Fossilized Drake",
    "Fossilized Fish",
    "Fresh Water",
    "Fresh-Start Mochi",
    "Friend Ball",
    "Full Heal",
    "Full Incense",
    "Full Restore",
    "Galarica Cuff",
    "Galarica Twig",
    "Galarica Wreath",
    "Galladite",
    "Ganlon Berry",
    "Garchompite",
    "Gardevoirite",
    "Gengarite",
    "Genius Feather",
    "Genius Mochi",
    "Gentle Mint",
    "Ghost Gem",
    "Ghost Memory",
    "Ghost Tera Shard",
    "Ghostium Z",
    "Gigantamix",
    "Gigaton Ball",
    "Glalitite",
    "Gold Bottle Cap",
    "Golden Nanab Berry",
    "Golden Pinap Berry",
    "Golden Razz Berry",
    "Grass Gem",
    "Grass Memory",
    "Grass Tera Shard",
    "Grassium Z",
    "Grassy Seed",
    "Great Ball",
    "Green Apricorn",
    "Green Scarf",
    "Green Shard",
    "Grepa Berry",
    "Grip Claw",
    "Griseous Core",
    "Griseous Orb",
    "Grit Dust",
    "Grit Gravel",
    "Grit Pebble",
    "Grit Rock",
    "Ground Gem",
    "Ground Memory",
    "Ground Tera Shard",
    "Groundium Z",
    "Guard Spec",
    "Gyaradosite",
    "Haban Berry",
    "Hard Stone",
    "Hasty Mint",
    "Heal Ball",
    "Heal Powder",
    "Health Candy",
    "Health Candy L",
    "Health Candy XL",
    "Health Feather",
    "Health Mochi",
    "Heart Scale",
    "Heat Rock",
    "Heavy Ball",
    "Heavy-Duty Boots",
    "Helix Fossil",
    "Heracronite",
    "Hi-tech Earbuds",
    "Hondew Berry",
    "Honey",
    "Hopo Berry",
    "Houndoominite",
    "HP Up",
    "Hyper Potion",
    "Iapapa Berry",
    "Ice Gem",
    "Ice Heal",
    "Ice Memory",
    "Ice Stone",
    "Ice Tera Shard",
    "Icicle Plate",
    "Icium Z",
    "Icy Rock",
    "Impish Mint",
    "Incinium Z",
    "Insect Plate",
    "Intriguing Stone",
    "Iron",
    "Iron Ball",
    "Iron Plate",
    "Item Urge",
    "Jaboca Berry",
    "Jet Ball",
    "Jolly Mint",
    "Kangaskhanite",
    "Kasib Berry",
    "Kebia Berry",
    "Kee Berry",
    "Kelpsy Berry",
    "Kings Leaf",
    "Kings Rock",
    "Kofus Wallet",
    "Lagging Tail",
    "Lansat Berry",
    "Latiasite",
    "Latiosite",
    "Lava Cookie",
    "Lax Incense",
    "Lax Mint",
    "Leaden Ball",
    "Leaders Crest",
    "Leaf Letter",
    "Leaf Stone",
    "Leek",
    "Leftovers",
    "Legend Plate",
    "Lemonade",
    "Leppa Berry",
    "Level Ball",
    "Liechi Berry",
    "Life Orb",
    "Light Ball",
    "Light Clay",
    "Linking Cord",
    "Loaded Dice",
    "Lone Earring",
    "Lonely Mint",
    "Lopunnite",
    "Love Ball",
    "Love Sweet",
    "Lucarionite",
    "Luck Incense",
    "Lucky Egg",
    "Lucky Punch",
    "Lum Berry",
    "Luminous Moss",
    "Lumiose Galette",
    "Lunalium Z",
    "Lure",
    "Lure Ball",
    "Lustrous Globe",
    "Lustrous Orb",
    "Luxury Ball",
    "Lycanium Z",
    "Macho Brace",
    "Magmarizer",
    "Magnet",
    "Mago Berry",
    "Magost Berry",
    "Malicious Armor",
    "Manectite",
    "Maranga Berry",
    "Marshadium Z",
    "Master Ball",
    "Masterpiece Teacup",
    "Mawilite",
    "Max Elixir",
    "Max Ether",
    "Max Honey",
    "Max Lure",
    "Max Mushrooms",
    "Max Potion",
    "Max Repel",
    "Max Revive",
    "Meadow Plate",
    "Medichamite",
    "Mental Herb",
    "Metagrossite",
    "Metal Alloy",
    "Metal Coat",
    "Metal Powder",
    "Metronome",
    "Mewnium Z",
    "Mewtwonite X",
    "Mewtwonite Y",
    "Micle Berry",
    "Mighty Candy",
    "Mighty Candy L",
    "Mighty Candy XL",
    "Mild Mint",
    "Mimikium Z",
    "Mind Plate",
    "Miracle Seed",
    "Mirror Herb",
    "Misty Seed",
    "Modest Mint",
    "Moomoo Milk",
    "Moon Ball",
    "Moon Stone",
    "Muscle Band",
    "Muscle Feather",
    "Muscle Mochi",
    "Mushroom Cake",
    "Mysterious Shard L",
    "Mysterious Shard S",
    "Mystic Water",
    "Naive Mint",
    "Nanab Berry",
    "Naughty Mint",
    "Nest Ball",
    "Net Ball",
    "Never-Melt Ice",
    "Nomel Berry",
    "Normal Gem",
    "Normal Tera Shard",
    "Normalium Z",
    "Nugget",
    "Occa Berry",
    "Oceanic Slate",
    "Odd Incense",
    "Odd Keystone",
    "Old Amber",
    "Old Gateau",
    "Oran Berry",
    "Origin Ball",
    "Origin Ore",
    "Oval Charm",
    "Oval Stone",
    "Pamtre Berry",
    "Paralyze Heal",
    "Park Ball",
    "Pass Orb",
    "Passho Berry",
    "Payapa Berry",
    "Pearl",
    "Pearl String",
    "Peat Block",
    "Pecha Berry",
    "Permit",
    "Persim Berry",
    "Petaya Berry",
    "Pewter Crunchies",
    "Pidgeotite",
    "Pikanium Z",
    "Pikashunium Z",
    "Pinap Berry",
    "Pink Apricorn",
    "Pink Bottle",
    "Pink Nectar",
    "Pink Scarf",
    "Pinsirite",
    "Pixie Plate",
    "Plasma Card",
    "Plume Fossil",
    "Plump Beans",
    "Poison Barb",
    "Poison Gem",
    "Poison Memory",
    "Poison Tera Shard",
    "Poisonium Z",
    "Poké Ball",
    "Poké Doll",
    "Poké Toy",
    "Polished Mud Ball",
    "Pomeg Berry",
    "Pop Pod",
    "Potion",
    "Power Anklet",
    "Power Band",
    "Power Belt",
    "Power Bracer",
    "Power Herb",
    "Power Lens",
    "Power Plant Pass",
    "Power Weight",
    "PP Max",
    "PP Up",
    "Premier Ball",
    "Pretty Feather",
    "Primarium Z",
    "Prism Scale",
    "Prison Bottle",
    "Protective Pads",
    "Protector",
    "Protein",
    "Psychic Gem",
    "Psychic Memory",
    "Psychic Seed",
    "Psychic Tera Shard",
    "Psychium Z",
    "Punching Glove",
    "Pure Incense",
    "Purple Nectar",
    "Qualot Berry",
    "Quick Ball",
    "Quick Candy",
    "Quick Candy L",
    "Quick Candy XL",
    "Quick Claw",
    "Quick Powder",
    "Quiet Mint",
    "Rabuta Berry",
    "Rage Candy Bar",
    "Rainbow Slate",
    "Rare Bone",
    "Rare Candy",
    "Rash Mint",
    "Rawst Berry",
    "Razor Claw",
    "Razor Fang",
    "Razz Berry",
    "Reaper Cloth",
    "Red Apricorn",
    "Red Card",
    "Red Flute",
    "Red Nectar",
    "Red Scarf",
    "Red Shard",
    "Relaxed Mint",
    "Relic Band",
    "Relic Copper",
    "Relic Crown",
    "Relic Gold",
    "Relic Silver",
    "Relic Statue",
    "Relic Vase",
    "Repeat Ball",
    "Repel",
    "Reset Urge",
    "Resist Feather",
    "Resist Mochi",
    "Reveal Glass",
    "Revival Herb",
    "Revive",
    "Ribbon Sweet",
    "Rindo Berry",
    "Ring Target",
    "Rock Gem",
    "Rock Incense",
    "Rock Memory",
    "Rock Tera Shard",
    "Rockium Z",
    "Rocky Helmet",
    "Roller Skates",
    "Room Service",
    "Root Fossil",
    "Rose Incense",
    "Roseli Berry",
    "Rowap Berry",
    "Sablenite",
    "Sachet",
    "Sacred Ash",
    "Safari Ball",
    "Safety Goggles",
    "Salac Berry",
    "Salamencite",
    "Salty Herba Mystica",
    "Sassy Mint",
    "Sceptilite",
    "Scizorite",
    "Scope Lens",
    "Sea Incense",
    "Serious Mint",
    "Shalour Sable",
    "Sharp Beak",
    "Shed Shell",
    "Shell Bell",
    "Shiny Charm",
    "Shiny Stone",
    "Shoal Salt",
    "Shoal Shell",
    "Shock Drive",
    "Shuca Berry",
    "Silk Scarf",
    "Silver Nanab Berry",
    "Silver Pinap Berry",
    "Silver Powder",
    "Silver Razz Berry",
    "Sitrus Berry",
    "Skull Fossil",
    "Sky Plate",
    "Slowbronite",
    "Smart Candy",
    "Smart Candy L",
    "Smart Candy XL",
    "Smoke Ball",
    "Smooth Rock",
    "Snorlium Z",
    "Snowball",
    "Soda Pop",
    "Soft Sand",
    "Solganium Z",
    "Soothe Bell",
    "Soul Dew",
    "Sour Herba Mystica",
    "Spell Tag",
    "Spelon Berry",
    "Spicy Herba Mystica",
    "Splash Plate",
    "Spooky Plate",
    "Sport Ball",
    "Sprinklotad",
    "Star Piece",
    "Star Sweet",
    "Stardust",
    "Starf Berry",
    "Stealth Spray",
    "Steel Gem",
    "Steel Memory",
    "Steel Tera Shard",
    "Steelium Z",
    "Steelixite",
    "Sticky Barb",
    "Stone Plate",
    "Strange Ball",
    "Strawberry Sweet",
    "Sun Stone",
    "Super Lure",
    "Super Potion",
    "Super Repel",
    "Swampertite",
    "Sweet Apple",
    "Sweet Heart",
    "Sweet Herba Mystica",
    "Swift Feather",
    "Swift Mochi",
    "Syrupy Apple",
    "Tamato Berry",
    "Tanga Berry",
    "Tapunium Z",
    "Tart Apple",
    "Tera Orb",
    "Terrain Extender",
    "Thick Club",
    "Throat Spray",
    "Thunder Stone",
    "Timer Ball",
    "Timid Mint",
    "Tiny Mushroom",
    "TMV Pass",
    "Tough Candy",
    "Tough Candy L",
    "Tough Candy XL",
    "Toxic Orb",
    "Toxic Plate",
    "Twisted Spoon",
    "Tyranitarite",
    "Ultra Ball",
    "Ultranecrozium Z",
    "Unremarkable Teacup",
    "Upgrade",
    "Utility Umbrella",
    "Venusaurite",
    "Wacan Berry",
    "Water Gem",
    "Water Memory",
    "Water Stone",
    "Water Tera Shard",
    "Waterium Z",
    "Watmel Berry",
    "Wave Incense",
    "Weakness Policy",
    "Wepear Berry",
    "White Apricorn",
    "White Flute",
    "White Herb",
    "Wide Lens",
    "Wiki Berry",
    "Wing Ball",
    "Wise Glasses",
    "Wishing Piece",
    "X Accuracy",
    "X Attack",
    "X Defense",
    "X Sp Atk",
    "X Sp Def",
    "X Speed",
    "Yache Berry",
    "Yellow Apricorn",
    "Yellow Flute",
    "Yellow Nectar",
    "Yellow Scarf",
    "Yellow Shard",
    "Zap Plate",
    "Zinc",
    "Zoom Lens"
  ];

  // Define word lists and corresponding responses
  const wordLists = [
    {
      words: runners,
      response: "Hangman game started with Pokémon Speedruners! Use !guess to guess a letter/number or the full runner's name."
    },
    {
      words: items,
      response: "Hangman game started with Pokémon Items! Use !guess to guess a letter/symbol or the full item's name."
    }
  ];

  // Create a new Random instance
  const random = new Random();

  // Choose a random list index
  const randomListIndex = random.integer(0, wordLists.length - 1);

  // Choose the selected list of words and corresponding response
  const { words, response } = wordLists[randomListIndex];

  // Choose a random word from the selected list
  const randomWord = words[random.integer(0, words.length - 1)];

  hangmanChannels[target] = {
    game: new HangmanGame(randomWord),
    lastGuessTime: Date.now(),
    cooldown: true,
  };

  // Append hidden word to response
  const finalResponse = `${response} Hidden word: ${hangmanChannels[target].game.hiddenWord}`;

  client.say(target, finalResponse);

  const timeoutId = setTimeout(() => {
    endHangman(target, client, 'inactivity');
  }, 15 * 60 * 1000); // 15 minutes timeout for inactivity

  hangmanChannels[target].timeoutId = timeoutId; // Store the timeout ID for this channel
}

function endHangman(target, client, reason) {
  const hangmanChannel = hangmanChannels[target];
  if (!hangmanChannel?.game) return; // Check if the hangmanChannel and game exist, if not, return

  const hangmanGame = hangmanChannel.game;
  const result = hangmanGame.isGameOver() ? 'lost' : 'won';
  const originalWord = hangmanGame.originalWord;

  if (reason === 'inactivity') {
    client.say(target, `Hangman game was running for too long. Next time try to be faster :). The word was: ${originalWord}. Next round starts in 5 minutes.`);
  } else {
    client.say(target, `Hangman round over! You ${result}. The word was: ${originalWord}. Next round starts in 5 minutes.`);
  }

  clearTimeout(hangmanChannel.timeoutId); // Clear the inactivity timeout for this channel
  hangmanChannel.cooldown = true; // Prevent automatic game start

  hangmanChannels[target].cooldown = true; // Set cooldown after the game ends
  setHangmanCooldown(target, client); // Set the global cooldown for !hangman command

  delete hangmanChannels[target]; // Remove the hangmanChannel entry for this channel
}

function setHangmanCooldown(target, client) {
  // Set a 5-minute cooldown for the !hangman command in this channel
  hangmanCooldowns[target] = Date.now() + 5 * 60 * 1000;

  // Schedule a message to be sent after the cooldown period is over
  setTimeout(() => {
    client.say(target, 'Hangman is available again. Use !hangman to start a new game.');
  }, 5 * 60 * 1000); // 5 minutes
}

// Initialize cooldown timestamp for hangman already active response
let lastHangmanActiveResponseTime = 0;

// Initialize cooldown timestamp for hangman not active response
let lastHangmanResponseTime = 0;

function handleHangmanCommands(target, client, context, msg) {
  const hangmanChannel = hangmanChannels[target];
  const sanitizedMsg = sanitizeInput(msg); // Sanitize user input

  const hangmanMatch = sanitizedMsg.match(/^!hangman/);
  const guessMatch = sanitizedMsg.match(/^!guess (.+)/);

  if (hangmanMatch) {
    if (hangmanCooldowns[target] && hangmanCooldowns[target] > Date.now()) {
      // Do nothing, let the cooldown message handle this case
    } else if (!hangmanChannel || !hangmanChannel.cooldown) {
      startHangman(target, client);
    } else {
      const now = Date.now();
      const cooldown = 60000; // 1 minute cooldown

      if (now - lastHangmanActiveResponseTime >= cooldown) {
        client.say(target, 'Hangman game is already active. Use !guess to play.');
        lastHangmanActiveResponseTime = now;
      }
    }
  } else if (guessMatch) {
    if (!hangmanChannel || !hangmanChannel.game) {
      const now = Date.now();
      const cooldown = 60000; // 1 minute cooldown

      if (now - lastHangmanResponseTime >= cooldown) {
        client.say(target, 'Hangman is currently not active.');
        lastHangmanResponseTime = now;
      }
    } else {
      hangmanChannel.lastGuessTime = Date.now(); // Update the last guess time

      const guess = guessMatch[1].toLowerCase();
      const hangmanGame = hangmanChannel.game;

      if (guess === hangmanGame.word) {
        client.say(target, `@${context.username} You guessed the word! Congratulations, you win!`);
        endHangman(target, client, 'win');
      } else if (guess.length === 1) {
        const success = hangmanGame.guess(guess);
        if (success) {
          client.say(target, `@${context.username} You guessed ${guess} . Hidden name: ${hangmanGame.hiddenWord}`);
          if (hangmanGame.isGameOver()) {
            endHangman(target, client, 'loss');
          } else if (hangmanGame.isGameWon()) {
            client.say(target, `@${context.username} You guessed the word! Congratulations, you win!`);
            endHangman(target, client, 'win');
          }
        } else {
          client.say(target, `@${context.username} You already guessed ${guess} .`);
        }
      } else {
        client.say(target, `@${context.username} Please guess one letter or the full word.`);
      }
    }
  }
}

module.exports = {
  handleHangmanCommands,
  setHangmanCooldown,
};