// randrunner.js

const { Random } = require('random-js');

const runner_list = [
  "Amoeba UK",
  "Exari onU",
  "wer ster",
  "Shiru 666",
  "Kukk er",
  "sizzle skeleton",
  "poke guy",
  "Gunner maniac",
  "Swif talu",
  "scoa gogo",
  "Mach Wing",
  "Kid rocker96",
  "driek iann",
  "edda ket",
  "Wh0mis DS",
  "CasualPoke Player",
  "Ender born",
  "JP Xinnam",
  "kur ddt",
  "SL weed",
  "Van dio",
  "3rd Jester",
  "Slayer LoL99",
  "5upa mayne",
  "craft ed",
  "Ana nan",
  "cater knees",
  "the waffleman",
  "Wave Warrior",
  "dec sy",
  "Extra Tricky",
  "Dabom stew",
  "Keiza ron",
  "gif vex",
  "entr pntr",
  "string flow",
  "New Amber",
  "G Shark54",
  "israr cool22",
  "Jord an97",
  "lucky typhlosion",
  "Mad diicT",
  "Ranger Squid",
  "Spark le",
  "_ PoY",
  "wink market",
  "AE tienne",
  "thunder _147_",
  "Ti Kevin83",
  "randall eatscheese",
  "ringo 777",
  "mindof damon",
  "Que laagging",
  "Vin cento",
  "Sin star",
  "Affected Ashes",
  "Pulse Effects",
  "Juanly ways",
  "Retro tato",
  "line washere",
  "Head bob",
  "Corvi mae",
  "Thomas PatrickWX",
  "Bungied 2thetree",
  "Garfield TheLightning",
  "head strong1290",
  "San jan",
  "Tip pi",
  "Et chy",
  "fran chewbacca",
  "knox conary",
  "JT Magicman",
  "Sheltie Sci",
  "Iron dre_",
  "cooltrainer michael",
  "true ly",
  "Pickle Plop",
  "Q palz98",
  "Ara ya",
  "Luck less",
  "LoveSick Hero",
  "BangYong Guk97",
  "Anal pikachu",
  "primal pizza",
  "hwang bro",
  "Yuji to",
  "Der Teppich",
  "em ray",
  "square _sr",
  "stoc chi",
  "TehHammer Show",
  "GoodAtBeing Simple",
  "Econ Sean",
  "I_only_say_ VoHiYo",
  "Legend Eater",
  "callum bal",
  "Alan Schweitzer",
  "Fract NL",
  "Ocean Bagel",
  "Crr ool",
  "Main 97",
  "themath genius",
  "ry ziken",
  "zek eke",
  "min now",
  "TheLime Films",
  "Boun xii",
  "Ruben tus",
  "Saiyan Cinq",
  "The KRAM",
  "Buster _poke",
  "MoneyHype Mike",
  "hal qery",
  "The4th GenGamer",
  "Ekman Larsson",
  "ito taka1031",
  "Oh _Snap",
  "ker bis54",
  "jy ash4",
  "zy potic",
  "EdHead SR",
  "pun yuta",
  "Tucker LeRat",
  "Gim my",
  "nerdy nerd32",
  "Kjoe ran",
  "chippy toothy",
  "Nix 644",
  "Shen anagans",
  "AB Twisty",
  "TTS4 Life",
  "Al w0",
  "keeping iticy",
  "Blu Magma",
  "epicdude guy",
  "Kyu tora",
  "bill bonzai",
  "Gal ino",
  "Par az10",
  "uw sellan",
  "Syl wer328",
  "Matt 59620",
  "Sly woo",
  "Cay oche",
  "Whar ax",
  "splen didz",
  "Yak sooo",
  "war tab",
  "ta his9",
  "Hypno shark",
  "Pra bxz",
  "Da kuuu",
  "Jie lefe",
  "Flame _SR",
  "Myst S4",
  "Plot wyx",
  "bahamut 3359",
  "HE4T R4N",
  "Beber Vorpal",
  "Lucas PGLP",
  "Vad nika",
  "Cer pin",
  "prie R57",
  "Noy lls",
  "joy lin728",
  "As pect"
];

// Create a new Random instance
const random = new Random();

// Function called when the "!randrunner" command is issued
function randrunnerCommand(target, client, context) {
  const start = getRandomNamePart(runner_list);
  const end = getRandomNamePart(runner_list);

  const combinedName = `${start}${end}`;
  client.say(target, `@${context.username} Your random runner name is: ${combinedName}`);
}

// Helper function to get a random name part from the list
function getRandomNamePart(nameList) {
  const randomEntry = random.pick(nameList);
  const randomNameParts = randomEntry.split(' ');
  return random.pick(randomNameParts);
}

module.exports = {
  randrunnerCommand,
};