// randomfact.js

//Random Facts
const listOfFacts = [

    {Fact: "A blue whales tongue can weigh as much as an entire elephant."},
    {Fact: "The world record for non-stop push ups is a whopping 10.507, done by Minoru Yoshida in 1980."},
    {Fact: "Planet Earth is 149.600.000 kilometers (92.957.130 miles) away from the sun."},
    {Fact: "The tallest man ever, named Robert Wadlow, was an oustanding 272 centimeters (8 ft. 11.1 in.) tall."},
    {Fact: "The scientific term for brain freeze is “sphenopalatine ganglioneuralgia”."},
    {Fact: "At birth, a baby panda is smaller than a mouse."},
    {Fact: "The Lego Group is the worlds most powerful brand. There are more Lego Minifigures than there are people on Earth."},
    {Fact: "There is a boss in Metal Gear Solid 3 that can be defeated by not playing the game for a week; or by changing the date."},
    {Fact: "There is an island called “Just Enough Room”, where theres just enough room for a tree and a house."},
    {Fact: "People who post their fitness routine on Facebook are more likely to have psychological problems."},
    {Fact: "A wildlife technician, Richard Thomas, took the famous tongue twister, “how much wood would a woodchuck chuck if a woodchuck could chuck wood” and calculated a rough estimate of what the answer would actually be. It came out to be around 700 pounds."},
    {Fact: "In Australia, there are nearly twice the amount of kangaroos as there are humans."},
    {Fact: "Crows can remember the faces of individual humans. They can also hold a grudge."},
    {Fact: "Strategic incompetence is the art of avoiding certain tasks by pretending you don't know how to do them."},
    {Fact: "Originally, the Pokemon Vulpix was going to be called FoxFire."},
    {Fact: "The odds of being born on 29th February are 1 in 1461."},
    {Fact: "Allodoxaphobia is the fear of opinions."},
    {Fact: "A snail can sleep for 3 years."},
    {Fact: "Fungus are more closely related to animals on a genetic level than they are to plants."},
    {Fact: "The largest living thing on earth is a giant sequoia named General Sherman."},
    {Fact: "There are over 6,000 known species of grass."},
    {Fact: "Aggressive sitting is a sport. It originated in Berlin no later than 2008. You can purchase a special stool for this sport for around 70 dollars."},
    {Fact: "George Miller - the person who created Mad Max is the same person who created Happy Feet."},
    {Fact: "The mongoose is one of those rare animals that is immune to a snake's venom."},
    {Fact: "Arachibutyrophobia is the fear of peanut butter sticking to the roof of the mouth."},
    {Fact: "There is a company in Japan that has schools that teach you how to be funny. The first one opened in 1982. About 1,000 students take the course each year."},
    {Fact: "A sunset on Mars is blue."},
    {Fact: "Elephants can die of a broken heart if their mate dies."},
    {Fact: "30 of the first 31 popes were murdered. Most of them were martyred, but not all causes of their deaths are known."},
    {Fact: "The center of a comet is called a nucleus."},
    {Fact: "The serial number on Darth Vader's suit of armor was E-3778Q-1."},
    {Fact: "A 23 sided shape is called an Icosakaitrigon."},
    {Fact: "A water dropwort is a highly poisonous plant. If it kills you, it can cause you to smile after you die. This is called a sardonic grin."},
    {Fact: "The goliath frog is the largest frog in the world and can grow up to 12.5inch (32cm) in length, and weigh up to 7.2 pounds (3.3kg)."},
    {Fact: "A woman once tried to commit suicide by jumping off the Empire State Building. She jumped from the 86th floor but was blown back onto the 85th floor by a gust of wind."},
    {Fact: "Jack Daniel (the founder of the whiskey) died from kicking a safe. When he kicked it, he broke his toe which got infected. He eventually died from blood poisoning."},
    {Fact: "The swan has over 25,000 feathers on its body."},
    {Fact: "The Guinness World Record for the time longest spend searching for the Loch Ness Monster, is held by Steve Feltham who camped at Loch Ness for 25 years."},
    {Fact: "In feudal Japan, lords purposely built homes with squeaky floors as a defensive measure against ninjas."},
    {Fact: "Alaska is the only state in America that can be typed on one row of a traditional English QWERTY keyboard."},
    {Fact: "The Earth is the only planet in our solar system not named after either a Greek or Roman God."},
    {Fact: "In 1992, a shipping crate containing 28,000 rubber duckies fell overboard. They washed up around the world for the next 20 years."},
    {Fact: "Nutella was invented during WWII, when an Italian pastry maker mixed hazelnuts into chocolate to extend his chocolate ration."},
    {Fact: "Saturn is so big that Earth could fit into it 755 times!"},
    {Fact: "Turkey vultures use defensive vomit to get rid of any disturbing animal. They can propel their vomit up to 10 feet."},
    {Fact: "Uncle Phil from Fresh Prince of Bel-Air was also the voice of Shredder from the original Teenage Mutant Ninja Turtles cartoon."},
    {Fact: "Octopuses only touch in situations of mating or aggression. Female octopuses sometimes do both, strangling and eating the male after mating."},
    {Fact: "There is a Guinness world record for the longest amount of time needed to create an official government - it is held by Belgium."},
    {Fact: "The sound of a Star Wars lightsaber was created by paring together the sound of an idle film projector and the buzz from an old TV set."},
    {Fact: "The only letter that doesnt appear on the periodic table is J."},
    {Fact: "Astronaut is a compound word derived from the two Ancient Greek words “Astro” meaning “star” and “naut” meaning “sailor”. So astronaut literally means “star sailor”."},
    {Fact: "The Lego Group is the worlds most powerful brand. There are more Lego Minifigures than there are people on Earth."},
    {Fact: "The voice actor of SpongeBob and the voice actor of Karen, Planktons computer wife, have been married since 1995."},
    {Fact: "IKEA is an acronym which stands for Ingvar Kamprad Elmtaryd Agunnaryd, which is the founders name, farm where he grew up, and hometown."},
    {Fact: "Standing around burns calories. On average, a 150-pound person burns 114 calories per hour while standing and doing nothing."},
    {Fact: "There is a town in Nebraska called Monowi with a population of one. The only resident is a woman who is the Mayor, Bartender, and Librarian."},
    {Fact: "Mercury and Venus are the only two planets in our solar system that do not have any moons."},
    {Fact: "Its not just humans who are right or left-handed. Most female cats prefer using their right paw and males are more likely to be left-pawed."},
    {Fact: "A bolt of lightning can reach 53,540 degrees Fahrenheit. Thats 5 times hotter than the surface of the sun, which is 10,340 degrees Fahrenheit."},
    {Fact: "Gaming-related accidents increased by 26.5% during the first 5 months of Pokémon Go being released. This included 2 deaths and $25.5 million in damages."},
    {Fact: "If you cut a starfish, it wont bleed – it doesnt have blood! Rather, they circulate nutrients by using seawater in their vascular system."},
    {Fact: "While shedding, geckos will eat their skin in order to prevent predators from finding and eating them more easily."},
    {Fact: "The word “velociraptor” comes from the Latin words “velox” which means swift, and “raptor” which means robber. Literally – speedy robber!"},
    {Fact: "Polar bears often hunt walruses by simply charging at a group of them and eating the ones that were crushed or wounded in the mass panic to escape. Direct attacks are rare."},
    {Fact: "When shuffling a deck of cards, the number of possible arrangements is approximately 8×10^67. Thats more than the number of stars in the observable universe."},
    {Fact: "The tallest mountain in our solar system, Olympic Mons, is 3 times taller than Mount Everest."},
    {Fact: "The blue whales heart is the size of a VW Beetle and weighs up to 1,000 lbs (453 kg)"},
    {Fact: "A man named Ronald MacDonald robbed a Wendys in 2005."},
    {Fact: "All of the clocks in the movie Pulp Fiction are stuck on 4:20."},
    {Fact: "Herring fish communicate by using flatulence."},
    {Fact: "An estimated 50% of all gold ever mined on Earth came from a single plateau in South Africa: Witwatersrand."},
    {Fact: "In Switzerland, it is illegal to flush the toilet after 10pm."},
    {Fact: "The money for the Statue of Liberty came from fundraising from auctions, a lottery, and boxing matches in Europe and the U.S. The Statue cost the French about $250,000, which today would be over $5.5 million dollars."},
    {Fact: "While filming Rocky IV, Lundgren hit Sylvester Stallone for real and he ended up in the hospital for nine days."},
    {Fact: "The little piece of paper sticking out of a Hersheys Kiss is called a niggly wiggly."},
    {Fact: "During the Second World War, German tank drivers would drive their vehicles over camel droppings, thinking it would bring them good luck."},
    {Fact: "A recently discovered deep sea snail, the Scaly-Food Gastropod, has a shell that is impressively developed. So much so, that the U.S. military is trying to use its design to inspire defensive layers in military armor."},
    {Fact: "There is a village in Russia called Tsovkra where every resident can tightrope walk. It is a tradition that dates back over 100 years but no one knows how it started."},
    {Fact: "A goldfish has a memory span of three seconds."},
    {Fact: "Most toilet paper sold for home use in France is pink."},
    {Fact: "The name for the shape of Pringles is called a “Hyperbolic Paraboloid”."},
    {Fact: "The thumbs up sign is believed to have originated from Chinese pilots. It was used to communicate with the ground crew before take-off."},
    {Fact: "Marvels Deadpool issue #27 holds the Guinness World Record for the most comic book characters on one cover."},
    {Fact: "Cruise ships have morgues that can store up to 10 bodies at once. The average amount of people that die on cruise ships per year is 200"},
    {Fact: "The phrase rule of thumb is derived from an old English law which stated that you couldn't beat your wife with anything wider than your thumb."},
    {Fact: "The characters Bert and Ernie on Sesame Street were named after Bert the cop and Ernie the taxi driver in Frank Capra's It's a Wonderful Life."},
    {Fact: "Tyromancy is the practice of predicting the future with cheese."},
    {Fact: "Flamingos turn pink due to the sheer amount of shrimp they consume."},
    {Fact: "The total weight of all air on Earth is 11 quintillion pounds."},
    {Fact: "All dogs are banned from Antarctica since April 1994. This ban was made because of concern that dogs might spread diseases to seals."},
    {Fact: "Ancient Romans used urine to whiten their teeth."},
    {Fact: "In Korea, there is a breed of dog called a Sapsali which was originally thought to banish ghosts and evil spirits."},
    {Fact: "The average American child is given $3.70 per tooth that falls out."},
    {Fact: "In World War II, Germany tried to collapse the British economy by dropping millions of counterfeit bills over London."},
    {Fact: "The highest body count in film history goes to “Lord of the Rings: Return of the King” with 836 on-screen deaths."},
    {Fact: "Thirty-five percent of the people who use personal ads for dating are already married."},
    {Fact: "The longest hiccupping attack lasted 68 years."},
    {Fact: "The first product Motorola started to develop was a record player for automobiles. At that time, the most known player on the market was Victrola, so they called themselves Motorola."},
    {Fact: "To prevent themselves from drifting apart, sea otters hold hands while they sleep."},
    {Fact: "When a male penguin falls in love with female penguin, he searches the entire beach to find the perfect pebble to present to her."},
    {Fact: "It is illegal to climb trees in Oshawa, a town in Ontario, Canada."},
    {Fact: "A bolt of lightning is six times hotter than the sun."},
    {Fact: "Having bridesmaids in a wedding wasnt originally for moral support. They were intended to confuse evil spirits or those who wished to harm the bride."},
    {Fact: "The eye of an ostrich is bigger than its brain."},
    {Fact: "The Pokemon Rhydon was the first to ever be created."},
    {Fact: "There were two AI chatbots created by Facebook to talk to each other, but they were shut down after they started communicating in a language they made for themselves."},
    {Fact: "If you cut down a cactus in Arizona, you will be penalized up to 25 years in jail. It is similar to cutting down a protected tree species."},
    {Fact: "German Chocolate Cake is named after an American baker by the name of Samuel German. It has no affiliation with the country of Germany."},
    {Fact: "The first service animals were established in Germany during World War I. References to service animals date as far back as the mid-16th Century."},
    {Fact: "Tirana, the capital of Albania has a lot of things in common with other European capitals – except one.  It is one of two capitals without a Mcdonalds. The second is Vatican City."},
    {Fact: "In 2009, Stephen Hawking held a reception for time travelers, but didnt publicize it until after. This way, only those who could time travel would be able to attend. Nobody else attended."},
    {Fact: "There are less than 30 ships in the Royal Canadian Navy which are less than most third-world countries."},
    {Fact: "The color red doesnt really make bulls angry; they are color-blind."},
    {Fact: "In 2007, Scotland spent £125,000 devising a new national slogan. The winning entry was: “Welcome to Scotland”."},
    {Fact: "Lettuce is a member of the sunflower family."},
    {Fact: "A cluster of bananas is called a “hand”. Along that theme, a single banana is called a “finger”."},
    {Fact: "The Ethiopian calendar is 7.5 years behind the Gregorian calendar due to the fact that it has 13 months."},
    {Fact: "The unique smell of rain actually comes from plant oils, bacteria, and ozone."},
    {Fact: "The Roman - Persian wars are the longest in history, lasting over 680 years. They began in 54 BC and ended in 628 AD."},
    {Fact: "The only window that opens on the presidential car is the driver's window, to pay tolls. It also has no keyholes, and only the Secret Service know how to open the doors."},
    {Fact: "A man with severe OCD and a phobia of germs attempted to commit suicide with a gun to his head. Instead of killing him, the bullet eliminated his mental illness without any other damage."},
    {Fact: "Dinosaurs that could run using just two legs are referred to as bipeds."},
    {Fact: "Whenever Charles Dickens was away from home, he would always realign the bed he was sleeping in to face Northwards, as he felt that this fostered and unlocked his creativity."},
    {Fact: "Comets only reflect 4% of the light that falls on them, the rest is absorbed."},
    {Fact: "There's a town in the Oklahoma panhandle named 'Hooker' and its slogan is 'it's a location, not a vocation'."},
    {Fact: "The same brain cycles that occur when asleep, still happen when you're awake, but in smaller sections. Meaning, parts of your brain are always 'falling asleep'."},
    {Fact: "Time anxiety occurs in a person when they are perpetually afraid of being late, or of others being late."},
    {Fact: "Jupiter completes a rotation of the Sun every 11.86 years."},
    {Fact: "Animal Planet aired two fake documentaries that 'proved' mermaids exist. So many people thought it was real that the U.S. government issued an official statement about it."},
    {Fact: "It takes Uranus 84 years to orbit the Sun once."}
  
  ];

// Function called when the "!randomfact" command is issued
function randomfactCommand(target, client) {
    const fact = rndfact();
    client.say(target, `${fact}`);
}

// Function called when the "!randomfact" command is issued
function rndfact () {
    const rndNum = Math.floor(Math.random () * listOfFacts.length);
    const facts = listOfFacts[rndNum].Fact;
    return facts;
}

module.exports = {
    randomfactCommand,
};